---

# - hosts: all
#   gather_facts: yes
#   roles:
#     - { role: bootstrap, tags: [ 'install', 'bootstrap', 'install-pdc', 'install-dc', 'install-fileserver' ] }

- hosts: all
  gather_facts: yes
  roles:
    - { role: samba4/hosts, tags: [ 'install', 'hosts', 'install-pdc', 'install-dc', 'install-fileserver' ] }

- hosts: pdc:dc
  gather_facts: yes
  roles:
    - { role: samba4/sysvol, tags: [ 'install', 'sysvol', 'install-pdc', 'install-dc' ] }

- hosts: all
  gather_facts: yes
  tasks:

    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ SAMBA_IMAGE }}"
        source: pull
      tags: [ 'pull', 'install', 'install-pdc', 'install-dc', 'install-fileserver' ]

- hosts: all
  gather_facts: yes
  roles:
    - { role: samba4/resolv, tags: [ 'resolv', 'install', 'install-pdc', 'install-dc', 'install-fileserver' ] }

- hosts: pdc
  gather_facts: yes
  roles:
    - { role: samba4/install, tags: [ 'install', 'install-pdc' ] }

- hosts: dc
  gather_facts: yes
  roles:
    - { role: samba4/install, tags: [ 'install', 'install-dc' ] }
    - { role: samba4/resolv, tags: [ 'resolv' ] }

- hosts: fileserver
  gather_facts: yes
  roles:
    - { role: samba4/install, tags: [ 'install', 'install-fileserver'] }

- hosts: all
  gather_facts: yes
  tasks:
    - name: Add samba-tool on host
      shell: echo 'docker exec -i samba-pdc samba-tool $*' > /usr/sbin/samba-tool && chmod +x /usr/sbin/samba-tool
      when: inventory_hostname in groups['pdc']
      tags: addons

    - name: Add samba-tool on host
      shell: echo 'docker exec -i samba-dc samba-tool $*' > /usr/sbin/samba-tool && chmod +x /usr/sbin/samba-tool
      when: inventory_hostname in groups['dc']
      tags: addons

    - name: Add samba-tool on host
      shell: echo 'docker exec -i samba-fs samba-tool $*' > /usr/sbin/samba-tool && chmod +x /usr/sbin/samba-tool
      when: inventory_hostname in groups['fileserver']
      tags: addons   

- hosts: all
  gather_facts: yes
  roles:
    - { role: samba4/smbconf, tags: [ 'smbconf' ] }
    - { role: samba4/restart, tags: [ 'restart' ] }
    - { role: samba4/fileserver, tags: [ 'fileserver' ] }
    - { role: samba4/restart, tags: [ 'restart' ] }
  

# - hosts: pdc:dc
#   gather_facts: yes
#   roles:    
#     - { role: samba4/fileserver, tags: [ 'fileserver' ] }

# - hosts: all
#   gather_facts: yes
#   roles:
#     - { role: samba4/addons, tags: addons }

#   tasks:
#     - name: Add samba-tool on host
#       shell: echo 'docker exec -it samba-pdc samba-tool $*' > /usr/sbin/samba-tool && chmod +x /usr/sbin/samba-tool
#       when: inventory_hostname in groups['pdc']
#       tags: addons

#     - name: Add samba-tool on host
#       shell: echo 'docker exec -i samba-dc samba-tool $*' > /usr/sbin/samba-tool && chmod +x /usr/sbin/samba-tool
#       when: inventory_hostname in groups['dc']
#       tags: addons

#     - name: Add samba-tool on host
#       shell: echo 'docker exec -i samba-fs samba-tool $*' > /usr/sbin/samba-tool && chmod +x /usr/sbin/samba-tool
#       when: inventory_hostname in groups['fileserver']
#       tags: addons      


# - hosts: fileserver
#   gather_facts: yes
#   roles:
#     - { role: samba4/fileserver/member, tags: [ 'member', 'memberfs' ] }

# - { role: samba4/fileserver/dc, tags: [ 'fileserver', 'dc' ] }

# - hosts: fileserver
#   gather_facts: yes
#   roles:
#     - { role: samba4/fileserver/member_dirs, tags: [ 'member', 'member_dirs' ] }

# - hosts: pdc
#   gather_facts: yes
#   tasks:
#     - name: Update DNS
#       shell: "samba_dnsupdate --all-names --verbose"


# - hosts: all
#   gather_facts: yes
#   roles:
#     - { role: samba4/audit, tags: [ 'audit', 'pdc', 'dc', 'member' ] }

# - hosts: pdc
#   gather_facts: yes
#   roles:
#     - { role: samba4/configuration/dns, tags: [ 'configs_dns', 'pdc' ] }
#     - { role: samba4/configuration/group_policies, tags: [ 'gpo', 'pdc' ] }
