
- name: Check if samba-pdc exist
  community.docker.docker_container_info:
    name: samba-pdc
  register: container_check_pdc

- name: Check if samba-dc exist
  community.docker.docker_container_info:
    name: samba-dc
  register: container_check_dc

- name: Apply GlusterD volume configuration
  ansible.builtin.template:
    src: glusterd.vol.j2
    dest: /etc/glusterfs/glusterd.vol
  when: not container_check_pdc.exists or not container_check_dc.exists

- name: Enable and start service Gluster
  ansible.builtin.systemd:
    name: glusterd.service
    enabled: yes
    state: restarted
  when: not container_check_pdc.exists or not container_check_dc.exists

- name: Samba | Sysvol Replication
  ansible.builtin.include_tasks: gluster-master.yml
  when: inventory_hostname in groups.pdc

- name: Samba | Sysvol Replication
  ansible.builtin.include_tasks: gluster-all.yml
  when: not container_check_pdc.exists or not container_check_dc.exists