---

# Create Folders

- name: Create Home Users Directory
  file:
    path: "{{ FILESERVER.SHARE_PATH }}/Users"
    state: directory
  when: SAMBA_HOME_USER is defined

- name: Create Public Directory
  file:
    path: "{{ FILESERVER.SHARE_PATH }}/Public"
    state: directory
  when: SAMBA_PUBLIC is defined

- name: Create Recycle Directory
  file:
    path: "{{ FILESERVER.SHARE_PATH }}/Recycle"
    state: directory
  when: SAMBA_RECYCLE is defined

# Chown Folders

- name: Chown Folders
  community.docker.docker_container_exec:
    container: "{{ item }}"
    command: /bin/bash -c 'chown root:"Domain Admins" /samba/shares/*'
  with_items:
    - samba-pdc
    - samba-dc
    - samba-fs
  ignore_errors: true

# Home User

- name: Set ACL of Home Users Folder
  shell: samba-tool ntacl set "O:LAG:DAD:PAI(A;OICI;0x001f01ff;;;LA)(A;OICI;0x001f01ff;;;DA)(A;OICIIO;0x001f01ff;;;CO)(A;;0x001200a9;;;DU)" /samba/shares/Users
  when: SAMBA_HOME_USER is defined

# Public

- name: Set ACL of Public Folder
  shell: samba-tool ntacl set "O:LAG:DAD:PAI(A;;0x001f01ff;;;LA)(A;;0x001f01ff;;;DA)(A;OICIIO;0x001301bf;;;CO)(A;OICIIO;0x001301bf;;;CG)(A;OICI;0x001301bf;;;DU)" /samba/shares/Public
  when: SAMBA_PUBLIC is defined

# Recycle

- name: Set ACL of Recycle Folder
  shell: samba-tool ntacl set "O:LAG:DAD:PAI(A;OICI;0x001f01ff;;;LA)(A;OICI;0x001f01ff;;;DA)(A;OICIIO;0x001f01ff;;;CO)(A;;0x001201bd;;;DU)" /samba/shares/Recycle
  when: SAMBA_RECYCLE is defined