- name: Update facts
  setup:
    gather_subset: min    

- name: Check if Samba Already installed
  stat:
    path: /var/lib/samba
  register: samba_directory

- name: Restart Docker
  systemd:
    name: docker
    state: restarted

- name: Pull Docker image
  docker_image:
    name: "{{ SAMBA_IMAGE }}"
    source: pull
  retries: 5
  delay: 3
  when: inventory_hostname in groups['masters'] or inventory_hostname in groups['dc']

- name: Pull Docker image
  docker_image:
    name: "{{ SAMBA_IMAGE_FILESERVER }}"
    source: pull
  retries: 5
  delay: 3
  when: inventory_hostname in groups['fileserver']

- name: Apply new resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Create Samba Container
  docker_container:
    name: samba-pdc
    image: "{{ SAMBA_IMAGE }}"
    state: started
    recreate: yes
    restart_policy: always
    network_mode: host
    privileged: yes
    hostname: "{{ inventory_hostname }}.{{ SAMBA_DC_REALM }}"
    env:
      SAMBA_DC_REALM: "{{ SAMBA_DC_REALM }}"
      SAMBA_DC_ADMIN_PASSWD: "{{ SAMBA_DC_ADMIN_PASSWD }}"
      SAMBA_DC_ACTION: provision
      SAMBA_DC_DOMAIN: "{{ SAMBA_DC_DOMAIN }}"
      SAMBA_INTERFACE: "{{ desired_interface_name }}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/samba:/var/lib/samba
      - /Sysvol:/var/lib/samba/sysvol
      - /etc/samba:/etc/samba
      - /var/log/samba:/var/log/samba
      - "{{ SAMBA_SHARE }}:/samba/shares"
  when: inventory_hostname in groups.masters

- name: Wait 60 seconds to continue
  pause:
    seconds: 60

- name: Create Samba Container
  docker_container:
    name: samba-dc
    image: "{{ SAMBA_IMAGE }}"
    state: started
    recreate: yes
    restart_policy: always
    network_mode: host
    privileged: yes
    hostname: "{{ inventory_hostname }}.{{ SAMBA_DC_REALM }}"
    env:
      SAMBA_DC_REALM: "{{ SAMBA_DC_REALM }}"
      SAMBA_DC_ADMIN_PASSWD: "{{ SAMBA_DC_ADMIN_PASSWD }}"
      SAMBA_DC_ACTION: join
      SAMBA_DC_DOMAIN: "{{ SAMBA_DC_DOMAIN }}"
      SAMBA_INTERFACE: "{{ desired_interface_name }}"
      SAMBA_DC_MASTER: "{{ hostvars[groups['masters'][0]]['ansible_host'] }}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/samba:/var/lib/samba
      - /Sysvol:/var/lib/samba/sysvol
      - /etc/samba:/etc/samba
      - /var/log/samba:/var/log/samba
      - "{{ SAMBA_SHARE }}:/samba/shares"
  when: inventory_hostname in groups.dc

- name: Wait 40 seconds to continue
  pause:
    seconds: 40

- name: Apply new resolv.conf
  template:
    src: resolv2conf.j2
    dest: /etc/resolv.conf

- name: Apply krb5
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
  when: inventory_hostname in groups.fileserver

- name: Create Samba Container
  docker_container:
    name: samba-fs
    image: "{{ SAMBA_IMAGE_FILESERVER }}"
    state: started
    recreate: yes
    restart_policy: always
    network_mode: host
    privileged: yes
    hostname: "{{ inventory_hostname }}.{{ SAMBA_DC_REALM }}"
    env:
      SAMBA_DC_REALM: "{{ SAMBA_DC_REALM }}"
      SAMBA_DC_ADMIN_PASSWD: "{{ SAMBA_DC_ADMIN_PASSWD }}"
      SAMBA_DC_ACTION: join
      SAMBA_DC_DOMAIN: "{{ SAMBA_DC_DOMAIN }}"
      SAMBA_INTERFACE: "{{ desired_interface_name }}"
      SAMBA_DC_MASTER: "{{ hostvars[groups['masters'][0]]['ansible_host'] }}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/krb5.conf:/etc/krb5.conf:ro
      - /etc/samba:/etc/samba
      - /var/log/samba:/var/log/samba
      - "{{ SAMBA_SHARE }}:/samba/shares"
  when: inventory_hostname in groups.fileserver

- name: Wait 60 seconds to continue
  pause:
    seconds: 60

- name: Backup idmap
  community.docker.docker_container_exec:
    container: samba-pdc
    command: /bin/bash -c "tdbbackup -s .bak /var/lib/samba/private/idmap.ldb"
  register: result
  when: inventory_hostname in groups['masters']

- name: Copy idpmap to DCs
  run_once: yes
  fetch: src=/var/lib/samba/private/idmap.ldb.bak dest=buffer/ flat=yes
  when: inventory_hostname in groups['masters']

- name: Copy idpmap to DCs
  copy: src=buffer/idmap.ldb.bak dest=/var/lib/samba/private/idmap.ldb
  when: inventory_hostname in groups['dc']
  retries: 5
  delay: 3

- name: Restart container samba-dc
  shell: docker restart samba-dc
  when: inventory_hostname in groups['dc']

- name: Wait 40 seconds to continue
  pause:
    seconds: 40

- name: Restart container samba-dc
  shell: docker restart samba-dc
  when: inventory_hostname in groups['dc']

- name: Restart container samba-fs
  shell: docker restart samba-fs
  when: inventory_hostname in groups['fileserver']

- name: Wait 15 seconds to continue
  pause:
    seconds: 15

- name: Reset Sysvol
  community.docker.docker_container_exec:
    container: samba-pdc
    command: /bin/bash -c "samba-tool ntacl sysvolreset"
  register: result
  when: inventory_hostname in groups['masters']

- name: Apply smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  when: not samba_directory.stat.exists

- name: Restart container samba-pdc
  shell: docker restart samba-pdc
  when: inventory_hostname in groups['masters']

- name: Wait 15 seconds to continue
  pause:
    seconds: 15

- name: Restart container samba-dc
  shell: docker restart samba-dc
  when: inventory_hostname in groups['dc']

- name: Wait 15 seconds to continue
  pause:
    seconds: 15

- name: Restart container samba-fs
  shell: docker restart samba-fs
  when: inventory_hostname in groups['fileserver']

- name: Wait 15 seconds to continue
  pause:
    seconds: 15